<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Commande supprimée</title>
</head>
<body style="height: 100vh; vertical-align: middle; text-align-center">
    La commande a été supprimée. Vous allez être redirigé(e).
</body>
</html>